# Generated by Django 4.2.1 on 2023-05-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_stock_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
